Alternative landingpage text (#12)
OpenHospitalityNetwork/openHospitality.network pull request #14
Opened 2021-07-05 13:40 UTC by aschrijver

In this PR I added the text from issue #12 to the README.md and created three sub-pages. The original README can be found in `learn-more.md` with the exception of the domain modeling paragraph, which I moved to `explore-functionality.md`.

I adapted the `header.html` to display entries for the sub-pages and move the mention of OpenCollective up on the page (also on small screens the sticky footer used before would overlap the header text in the old design).

2021-07-06 06:25 UTC, mariha commented
Two things for the flow, adding here as for the moment.

**How can I easily see the changes?**
- without opening ide, in the browser
   - should we auto-deploy each PR somewhere?
- in my IDE, to play with the code
   -  since it is not a branch, can not fetch and switch, need to update upstream

https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes
```
# check remote repos
git remote
git remote -v

# adding remote repo
git remote add <remote alias> <url>

git fetch <remote alias>
git pull --rebase <remote alias>
git push <remote alias> <branch>

git remote remove <remote alias>
```

2021-07-06 07:31 UTC, mariha requested changes
I would prefer to take some time to think about it, sorry if it makes bad contributor experience for you, it's just that it's not an easy one, because this **is** very personal, bicycle touring and letting go the page that I put so much effort into, most importantly though I think there are some differences in the vision the text builds and which I don't feel that much. But your text also just reads much better, I have to admit \_/(^\_^)\\\_.

I'll come back to it in the evening, a few quick things that I would rather keep the way they were before.
- I actually preferred when the Open Collective link was at the very bottom, unobtrusive but on it's own so didn't get lost among other stuff. WS was asking for donations way too pushy and it may be that I have to over-react. So if we run into financial troubles we can think about changing it. 
- help wanted reads better to me the way how I wrote it, it was more instructive with bolded parts that guides attention to the right parts. I also wanted bicycle touring community to start self-organize in TR contributors, I've discussed that with Mikael. But I guess we may want to include others who I haven't thought about.
- The left side panel: I prefer navigation to be straight forward, and the contact information gets lost and feels to me less inviting then as it was before, on the left side just short "Visit out:" (could be rephrased but also this seems ok) was better, imho
- I have no idea what to do with the other links, where to place them? Can we keep them out for a moment?

2021-07-06 07:31 UTC, mariha commented on README.md
> +>Our main objective is to avoid this commercial trend, and tread our own path forward. A path that involves people, and travelling together.
This is the sentence that holds me from releasing it, I'd like to take some time to think about it, pls.

2021-07-06 09:39 UTC, aschrijver commented
No rush, and no need to go with this text. I made it on own initiative. My alternative was giving lotsa feedback on structure and no action. I found the original text overwhelming, and I wasn't even a newcomer and had background knowledge. On reading I felt I needed to distill it, and there were so many bold-face highlights in "What will change".

If you'd ask me for improvement on current PR I would further compress it, shortening with more concise and comprehensible sentences until someone that lands on the site needs less than a minute to know what this is all about. Then - when interested - jumps into the appropriate sub-section of the site.

- I have no preference for OpenCollective position, but don't think the new place is in-your-face. It is `<small>` text too.
- The 2 panel sections can be swapped, so contact points come first. Think an easy drilldown to subsections is needed though.

2021-07-06 09:46 UTC, aschrijver commented on README.md
> +>Our main objective is to avoid this commercial trend, and tread our own path forward. A path that involves people, and travelling together.
I agree. We can make this better. If you ask me then this sentence should express the **Vision**, so that:

- **Mission** (that what we do): _We help keep online hospitality exchange open and uniquely social._
- **Vision** (that what we want to achieve): _We unify diverse traveller communities from all over the world._

Giving a proposal above. Note that in the vision there's no mention of internet or platforms or anything. It is phrased from the Needs, not the Means.

2021-07-06 23:10 UTC, mariha approved these changes
Hey Arnold, thanks for your patience!

I think it's amazing that you can write from someones else perspective so easily!

Your text reads much better than what I wrote, so it's better to release it then hold, but... could we just add a [Draft] note at the top? So to indicate that it's a work in progress and maybe link to what was before under that [Draft] text?

I left some comments what I'd rather write differently.

Thanks! Let's merge it and iterate from there.

2021-07-06 23:10 UTC, mariha commented on README.md
> +Showing kindness to guests and giving strangers a warm welcome, hospitality has always been part of human nature. Wonderful people who share with others, and exchange life's stories and adventures. T
I have to say that I really like these two first paragraphs. 

I'd only change slightly this sentence:
> Nowadays many hospitality exchange platforms exist where people can _plan their travels_.

I don't think people use hospex platforms to plan travels, _planning stays_ feels better for me, would also replace _planning_ with something else... For the WarmShowers survey:

### What do you look for when using WarmShowers.org?

**As a host:**
- 73.6% (787) As a host and guest: To meet and hangout with likeminded people, who share my passion for bicycle touring
- 65.4% (699) As a host: I am a traveler by myself, I have been there before and I just want to help
- 57.2% (612) As a host: To meet people from other cultures (cultural exchange)

**As a guest:**
- 73.6% (787) As a host and guest: To meet and hangout with likeminded people, who share my passion for bicycle touring
- 68.3% (730) As a guest: Sometimes I just need a shower, and a safe dry place to stay
- 63.9% (683) As a guest: To get to know people local to where I travel to (cultural exchange)
- 38.7% (414) As a guest: To avoid spending money on accommodation

**Other unique answers:**
- I truly believe in the connections between people, regardless of their colour, beliefs and ways or living.
- As a host: To be sure that people practicing bicycle touring can find easily free places to stay
- As a guest i live in my car
- receive goid advices from locals
- To make the world a bit nicer and live community ideas
- Use
- As a host : to help propose feel welcome and share our culture
- Meet people with shared interests outside of bike touring. Have little interest in talking bikes or loadouts.
- The focus on bicycle-Travellers!
- Help people enjoy life
- Sometimes life puts me into a situation and I need help. Reaching out to like minded fellow cyclists offer a helping hand.
- a beautiful mix of all of the above :)
- En alternative for Couchsurfing be welcome and trustroots
- To promote cycle touring through experience
- As an emergency, if there aren't camp grounds nearby
- As a host and a guest I love the idea of having workdwide travel more affordable and accessible to everyone!
- To make friends for live
- To be hosted by families or to host families to exchange about cycle touring with kids
- Karma
- We are no cyclists but do love to host not only cyclists. We are hiking and there is no platform. Exclusion of people not mainly cycling is not our mindset
- I need to know if the place is safe for queers and gender nom confirming people!
- Maybe to meet a future touring buddy
- Another option when planning overnight stays.
- Just as a principal, it's nice to host people for free!
- I am looking forward to use it as a guest as well in future
- I'm cyclist and like doing long travels. Jet I have not "warm showers"
- Cycle touring can get lonely and it's nice to see a friendly face once in a while
- To help strengthen our community of bikers/bike tourists by building a nationwide network.
- En francais svp
- warmshowers is/was a perfect combination of three of my passions: free software (sharing), bikes (ecological technology), and touring (cultural exchange)
- as a traveler, I want to be able to plan my trip. insights on places to stop along the way to work the roses, detours and route changes, bike shops and stores for repairs and supplies, available in my app even in the absence of cell service and with a strong emphasis on preserving battery. I'd also like an SOS function in case of mechanical troubles that would send a blanket mayday notification to nearby members
- Make like minded friends!
- As a guest, I enjoyed the family like feeling as though I were staying with an aunt/s and/or uncle/s. I love feeling taken care of and safe on the road. When my host was comfortable, I loved cooking for them to shared my passion for food and show my gratitude for their generosity!
- To get local input on planning decisions.
- open a house that I love much when free.

2021-07-06 23:10 UTC, mariha commented on README.md
> +However there is a problem that threatens the open hospitality culture. There's money to be earned from hospitality and commercial incentives have warped the values and ideals of some popular hospita
just fyi, I am not 100% sure if it was money or power or something else. I guess it's ok how you wrote it.

> It is time to make _a stand against_ the companies involved in this development

I'd rather just go our own way, no desire to stand agains anyone. We've tried to go together with WS for long time, it was just not possible any more. We just loved the people and spirit of this community and we'd like to rebuild it somewhere else, based on values how it was founded initially: openness and trust.

2021-07-06 23:10 UTC, mariha commented on README.md
> +>Our main objective is to avoid this commercial trend, and tread our own path forward. A path that involves people, and travelling together.
Thanks for the explanation! I personally don't feel strong need to have a mission and vision stated as everyone else does, but also have nothing against having them.

What about something along the lines:
> Our main objective is to preserve the communities despite this commercial trend, and there is no other choice left than to tread our own path forward. ~A path that involves people, and travelling together.~

The mission sounds good to me (as for now)
The vision... I guess this is not good?
> We strive to federate different hospitality exchange platforms to unify the community while enabling greater diversity and long term sustainability of all together.

by _sustainability_ I understand everlasting the founders and boards of directors.

or:
> We strive to create an open and transparent environment for the hospitality exchange communities to thrive.

2021-07-06 23:10 UTC, mariha commented on README.md
> +We’d like new communities to freely form, grow and evolve to keep serving their communities’ needs. Our primary focus is to learn from each other, to collaborate intricately and strenghten our common
> Our primary focus is to learn from each other, to collaborate intricately and strenghten our common path.

I don't think this is accurate. Maybe we could just skip it?

2021-07-06 23:10 UTC, mariha commented on README.md
> +- To integrate our services, so that guests and hosts are reachable from any platform.
I'd add _if they choose to_. 

People are concerned about not being able to close themselves in their own communities in Trustroots. Although this is not true, it shows that It's important for people to have choice who they want to host.

2021-07-06 23:10 UTC, mariha commented on README.md
> +- To explore best-practices for open governance, open-source software and open finances.
I love this one!

2021-07-07 01:30 UTC, weex commented
I'm reading "let's merge it" and that the PR is approved as an ok to click Merge but I also see some requests for changes. Is it ok to merge then?

2021-07-07 06:08 UTC, aschrijver commented on README.md
> +Showing kindness to guests and giving strangers a warm welcome, hospitality has always been part of human nature. Wonderful people who share with others, and exchange life's stories and adventures. T
Oh wow, this is great feedback. That bulleted list should be included somewhere in the exploration of the functionality in the sub-section.

How about:

> Nowadays many hospitality exchange platforms exist where guests meet hosts and find a place to stay.

2021-07-07 06:24 UTC, aschrijver commented on README.md
> +However there is a problem that threatens the open hospitality culture. There's money to be earned from hospitality and commercial incentives have warped the values and ideals of some popular hospita
Good points, and an important distinction you make. I agree.

I think the first part is okay. Commercialization and its effects is something that people can relate to in general. It is not always done with bad intentions, but it will often erode the quality of the initiative that existed before.

How about:

> It is time to go our own way and side firmly to the human camp, where people, openness and trust and the spirit of community will always prevail.

2021-07-07 06:38 UTC, mariha commented
Sorry for confusing, I forgot that Arnold is not the one who merges. 

I think from the process perspective:
1. nothing is broken
2. it is better then what it was \[first point on DoD]
3. it is a user visible change that we agreed we'd like to make (the previous text was not good)
4. The quality checks we could ask for (that could be supported by tools): correct syntax and language etc is great
5. Any tests to protect the change from being broken by future changes? I don't think it applies to text \[second point on DoD]
4. there is an issue as for me that it does more then making the text more clear: reorganizes structure/navigation/layout ie. OpenCollective, help wanted!, links to subpages which as for me could be initially kept in the text and treated separately. 

I think in this case probably we didn't define well enough the problem that we want to solve and didn't have enough discussion on the issue that Arnold first created before going forward with the PR (what was actually my fault because I asked him to open it). For things like mission we _could_ agree on them before ;) I can imagine also Arnold seeking more feedback from us more interpersonally while the code still sits in their private fork and is not requested to be integrated yet. Would love to know your thoughts on the process.

Overall, I'd say as for me **it is good to merge** and keep smoothly iterating on it, to address things that I mentioned. I'd say seek more feedback before creating a PR, based on your own best judgement what should be agreed on before. There are also draft PRs that could be used, maybe. From when a PR is created, I'd like to automate it (to prevent unintentional braking changes) and remove any human judgement from the merge process.

2021-07-07 06:48 UTC, aschrijver commented on README.md
> +We’d like new communities to freely form, grow and evolve to keep serving their communities’ needs. Our primary focus is to learn from each other, to collaborate intricately and strenghten our common
(Somehow I'm not allowed to comment on the review point above this one, so doing that here..)

Note that the text does not explicitly state 'this is our vision and this is our mission'. It leaves out those words so its not in-your-face, but you can refer to both easily if the need arises.

> Our main objective is to preserve the communities despite this commercial trend, and there is no other choice left than to tread our own path forward. ~~A path that involves people, and travelling together.~~

I'm fine with that, but probably have to review the entirety of the text to ensure there's no repeating of the same things in slightly different words.

> I guess this is not good?
>
>>We strive to federate different hospitality exchange platforms to unify the community while enabling greater diversity and long term sustainability of all together.

This is the text in the header as you wrote it, with 2 slight changes. I see this as neither mission or vision, but more a project summary. I like it. It has a bit more specificity in it with the word 'federate'.

>>Our primary focus is to learn from each other, to collaborate intricately and strenghten our common path.
>
>I don't think this is accurate. Maybe we could just skip it?

I think this important as it states the basis on which you participate. You are not bound by an obligation, and retain full independence to make your own choice. It's just a "stronger together" statement.

2021-07-07 06:50 UTC, aschrijver commented on README.md
> +- To integrate our services, so that guests and hosts are reachable from any platform.
Agreed.

2021-07-07 06:51 UTC, aschrijver commented on README.md
> +- To explore best-practices for open governance, open-source software and open finances.
It was already in your text, I just turned it into a specific bullet point :)

2021-07-07 07:01 UTC, aschrijver commented
I agree with you assessment. In this particular case - since the landing page changes were more of a complete replacement - talking them over in the issue would've been best.

As for merging.. I'd rather incorporate the feedback above in another commit before we do that, otherwise we'll have to redo the discussion.

Also there are at least 2 new GH issues we should create, imho: One about mission/vision (I will create) and one with the WS survey feedback and how we treat that (@mariha best create).

2021-07-07 08:38 UTC, mariha commented on README.md
> +Showing kindness to guests and giving strangers a warm welcome, hospitality has always been part of human nature. Wonderful people who share with others, and exchange life's stories and adventures. T
might be! I'd slightly prefer _travelers_ than _guests_.

What about:
> Nowadays many hospitality exchange platforms exist which help travelers and hosts find each other.

to emphasize symmetrical relation, that it's not only traveler who "benefits" from the exchange but a host as well! I personally enjoy _hosting_ more then _staying_ at someone's home. It feels like going on a trip without leaving home. There is also a comment in the survey from 83 years old guy who wrote he used to travel a lot and right now hosting kind of gives him the same spirit of adventure. Bicycle touring travelers are very amazing and adventurous people!

2021-07-07 08:54 UTC, mariha commented on README.md
> +However there is a problem that threatens the open hospitality culture. There's money to be earned from hospitality and commercial incentives have warped the values and ideals of some popular hospita
_human camp ..._ -> openness camp, built on trust and transparency, where people and the spirit of community will always prevail ?

You may also want to somehow reused what Saemy and I wrote in the message from developers (https://warmshowers.bike). I like very much what we came up with.

> Back in 2012, when this app was created(\*), WarmShowers was an open, free and welcoming platform. Since 2015, under the new board, WS has been slowly but steadily moving in the direction that **we can’t agree with any more**(\*\*). It’s time for us to go our own way.
>
> We are thinking about creating **a new platform** dedicated for the worldwide community of bicycle touring travelers and those who want to host them. One that is again **built on trust and openness**, that reflects values which drive people to open doors to their homes and welcome strangers traveling the world by bicycle. One that helps to build lifelong friendships which cross boundaries. **Free and transparent** for everyone forever.

2021-07-07 09:18 UTC, mariha commented on README.md
> +We’d like new communities to freely form, grow and evolve to keep serving their communities’ needs. Our primary focus is to learn from each other, to collaborate intricately and strenghten our common
>>> Our primary focus is to learn from each other, to collaborate intricately and strenghten our common path.
>>
>> I don't think this is accurate. Maybe we could just skip it?
>
> I think this important as it states the basis on which you participate. You are not bound by an obligation, and retain full independence to make your own choice. It's just a "stronger together" statement.

ah, I see. Good point. Somehow I thought it's about hospex communities learning from each other, collaborating etc...  What about:
> As individuals, our primary focus is to learn \[...\] As a team, our main goals are: 

Might also consider adding that we want to built something that we miss. 

You can imagine WS community as a group of outsiders who has just lost the only community they've ever felt part of. Many of them are not on social media, avoid huge gatherings, and prefer to spent time on their own rather than in a group. That's way I think it would be especially hard to rebuilt this community.

2021-07-07 18:28 UTC, aschrijver commented on README.md
> +Showing kindness to guests and giving strangers a warm welcome, hospitality has always been part of human nature. Wonderful people who share with others, and exchange life's stories and adventures. T
Good points. I agree.

2021-07-07 18:31 UTC, aschrijver commented on README.md
> +However there is a problem that threatens the open hospitality culture. There's money to be earned from hospitality and commercial incentives have warped the values and ideals of some popular hospita
I think the way you formulated above is best, but it should be "open camp" then, instead of openness camp, because I don't know what that would really mean :)

2021-07-07 18:33 UTC, aschrijver commented on README.md
> +We’d like new communities to freely form, grow and evolve to keep serving their communities’ needs. Our primary focus is to learn from each other, to collaborate intricately and strenghten our common
Yep. Will make that change.

2021-07-07 18:36 UTC, aschrijver commented on README.md
> +Showing kindness to guests and giving strangers a warm welcome, hospitality has always been part of human nature. Wonderful people who share with others, and exchange life's stories and adventures. T
@mariha could you copy the bullet lists above to a new issue e.g. "Community feedback on WarmShowers survey"?

2021-07-08 05:45 UTC, aschrijver commented on README.md
> +However there is a problem that threatens the open hospitality culture. There's money to be earned from hospitality and commercial incentives have warped the values and ideals of some popular hospita
I made the changes as suggested.

2021-07-08 06:09 UTC, aschrijver commented on README.md
> +We’d like new communities to freely form, grow and evolve to keep serving their communities’ needs. Our primary focus is to learn from each other, to collaborate intricately and strenghten our common
@mariha on the vision part, after typing it in the README some ponts to address..

Suggested change:

> Our main objective is to preserve the communities despite this commercial trend, and there is no other choice left than to tread our own path forward.

- "preserve communities" --> not progressive, ambitious (museum?)
- "no other choice left" --> we are forced, a dependency exists, but we are independent

How about:

> Our main objective is to foster community vibe and values without commercial influence, and tread our own path forward.

2021-07-08 06:23 UTC, aschrijver commented on README.md
> +- To integrate our services, so that guests and hosts are reachable from any platform.
I formulated as:

> - To decentralize our services, ensuring freedom of choice and democratic control.
> - To integrate our platforms, so that guests and hosts can choose to interact more broadly.

2021-07-08 06:24 UTC, aschrijver commented on README.md
> +>Our main objective is to avoid this commercial trend, and tread our own path forward. A path that involves people, and travelling together.
Resolving this, as it is discussed further below.

2021-07-08 06:32 UTC, aschrijver commented on README.md
> +Showing kindness to guests and giving strangers a warm welcome, hospitality has always been part of human nature. Wonderful people who share with others, and exchange life's stories and adventures. T
Resolving, as the survey feedback is now on Trello at https://trello.com/c/Vjc7a8R2

2021-07-08 06:46 UTC, mariha commented on README.md
> +- To integrate our services, so that guests and hosts are reachable from any platform.
Sounds good! 

One more thing... I prefer the word _traveler_ then _guest_ and as we are discussing here it seems to me even more important then initially. It may help us and others from accidentally sliding "hospitality exchange" into "chip accommodation alternative" which they are very distinctive. Let's try to use _traveler_ consistently.

2021-07-08 06:59 UTC, mariha commented on README.md
> +We’d like new communities to freely form, grow and evolve to keep serving their communities’ needs. Our primary focus is to learn from each other, to collaborate intricately and strenghten our common
> "preserve communities" --> not progressive, ambitious (museum?)

maybe 'preserve communities' is not the best one, what about _build resiliency into the communities despite this commercial trend_?

> "no other choice left" --> non-visionary. we are forced, a dependency exists, but we are independent

To be honest I prefer to be _authentic_ then _visionary_. Everyone nowadays is visionary, especially in the business, despite many lack imagination. And our communities are often anti-systemic and outside of the business world, they try to escape it! This is what bothers me most in these very round worlds (and why to some extent I preferred my technical speech), that this is a language that business speaks which we just try to oppose to. I don't know how to come around with that... do you think you could try to write more with an open and direct language instead?

2021-07-08 07:22 UTC, aschrijver commented on README.md
> +We’d like new communities to freely form, grow and evolve to keep serving their communities’ needs. Our primary focus is to learn from each other, to collaborate intricately and strenghten our common
I created a Trello card [Mission, vision, summary](https://trello.com/c/AciE6k4B/110-mission-vision-summary) for further discussion. Will refer to this review section, and then resolve.

2021-07-08 07:22 UTC, aschrijver commented on README.md
> +- To integrate our services, so that guests and hosts are reachable from any platform.
Resolving, we can iterate after new commits.

2021-07-08 08:15 UTC, aschrijver commented
@mariha I incorporated all feedback, except for OpenCollective placement. I used your Help wanted text, but with an improvement that we can discuss in the next iteration. I think this PR can be merged and then we can continue discussion in #12

2021-07-08 18:50 UTC, weex commented
Agree that this change tackles a lot but I think it's best to merge the latest, and next to define individually the smallest possible problems with the text which can be handled by their own PRs respectively.

2021-07-08 20:22 UTC, mariha reviewed
Hey Arnold, do you mind if we hold on with this PR? I feel like we lost a sense of direction where are we going with this.

Maybe we can decompose it into smaller parts, and do one at a time?

I also feel like it's quite important for this page to be authentic for people involved in hospitality exchange itself. I think what you wrote is good or even very good, it just doesn't feel like ours...

Let's talk tomorrow over the phone?

2021-07-08 22:10 UTC, aschrijver commented
No problem, though it would have been nice to hear that earlier. You can close or merge, authenticity prevails.

2021-07-09 04:37 UTC, aschrijver commented
Good morning @mariha . In response to your last GH comment on the site PR.. like I said at the start I don't mind really what you do with it. It was my choice to revamp the text.

The only thing that is a bit of a bummer is that the expectation was raised we'd "review, improve, then merge, and iterate from there" and based on that we spent a lot of time reviewing and improving already.

You have to feel comfortable with the project, and that is most important. By this reviewing I give my opinion on text variations of stuff I wrote, and though it may have led to some insight, it has pushed you out of your comfort zone, I feel. I am sorry if that is the case.

Also I tend to be meticulous in project preparation before launch with an eye on a total process that includes non-technical activities (community building, etc), whereas you and the others most likely want to just join the fun and start to code. And make this a 'deverloper-mostly' project at the start. I can understand that.

So I am happy to just step back quite a bit for now, and let ya'all shape any way you want. Personally I am still in the situation where I am doing too much advocacy and community things across the fedi to get to the coding fun I eventually want to have with Groundwork and the apps that should be built on top of that eventually.

2021-07-09 11:48 UTC, mariha commented
I am very sorry, didn't want it to come this way either.

> it has pushed you out of your comfort zone, I feel. I am sorry if that is the case.

Thanks. You are right.

As for a reference, and I hope this will help you understand my perspective: 
- the PR has more then what it was meant to do in [the issue](#12), it restructures navigation and layout in the way I am not in favor of, may just need some more discussion, but [I pointed it out to you](https://github.com/FediHospEx/fedihospex.github.io/pull/14#pullrequestreview-699602239) and [you decided to keep it](https://github.com/FediHospEx/fedihospex.github.io/pull/14#issuecomment-876232633) (funding and side panel)
- [reorganizing the project](https://trello.com/c/1R4D88Lf) despite we've already said that it's ok as for now and we want to focus on something else first (contribution guidelines, PoC, bicycle touring community)
- [changing the name of the project](https://github.com/FediHospEx/fedihospex.github.io/pull/14/commits/2cb98e76742f36a2652f2d990e6ca0d1598642a7) to the one of your preference, before [we settled down on a choice](https://trello.com/c/TO88UQfz)
- [changing summary of the project](https://github.com/FediHospEx/fedihospex.github.io/pull/14/commits/2cb98e76742f36a2652f2d990e6ca0d1598642a7) _try to_ -> _strive_ and many other corporate buzz words throughout the review convoluting the meaning and as for me authenticity, which were not easy for me but _hey! we were working on it!_ kept me positive about the outcomes... until it was too much.
- [this](https://github.com/FediHospEx/fedihospex.github.io/pull/14#discussion_r665895760): 
  > Suggested change:
  >
  > >Our main objective is to preserve the communities despite this commercial trend, and there is no other choice left than to tread our own path forward.
  >
  > "preserve communities" --> not progressive, ambitious (museum?)
  > "no other choice left" --> non-visionary. we are forced, a dependency exists, but we are independent
  >
  > How about:
  > >Our main objective is to foster community vibe and values without commercial influence, and tread our own path forward.
- [this](https://trello.com/c/AciE6k4B):
  >> We try to federate different hospitality exchange platforms to unify the community while enabling greater diversity and long term sustainability of all together.
  >
  > In the PR I changed and propose for Summary:
  > 
  > FediHospEx strives to federate different hospitality exchange platforms to unify diverse communities and ensure long term sustainability and resilience.
  > 
  > Rationale:
  > "enable greater diversity": diversity as used here is a hype and trend, to the extend where it loses meaning and there's  'diversity-washing'. The hospitality platforms are already diverse and unifying them naturally increases that.

  Fyi, I used diversity here from my genuine and deep belief in it, and understanding of what we want to do in this project, not as a hype and trend. I agree there is 'diversity-washing', might have experienced it, and I won't help that corporations turn things around so that those deepest and most important concepts become empty words. For me they are not empty. I meant exactly what I wrote (not that it can't be improved, especially that I am not a native speaker, but it was pretty close).

  I also don't think there is enough diversity among hospex platforms. I myself couldn't fit in trustroots (or any other except WS) because of the overweeningly communal flavor as for me, nor into too wide cyclists circle (cyclists ride for speed and km covered, I ride my bike for a sense of freedom it gives)

- and lastly, you [started to couch me](https://matrix.to/#/!gGjMmeyQavLEcOoVQX:chagai.website/$FjNtoz8al5ERYR9L7AKN4KS098fK7H4TUyxuGIOxfI0?via=matrix.org&via=chagai.website&via=feneas.org)! I've met enough managers and other good will people in my profesional life who wanted to _guide me_, and then once they gained my trust, left me when I needed their support most. And at this point, I don't believe I am _guidable_ any more, quite the opposite. They promised and reaffirmed me that they know the path despite they have never been there, and at the first bumps left me alone. 

  So many of well intentioned otherwise smart guys rely on this false assumption that they somehow fail to realize: they got where they are because they followed the same path as many generations of others similar to them followed before. And I got where I am because I _did not_ follow anyone. This is the very simple truth software engineering industry fails to understand, most women who are right now in engineering are non-conformists by nature, and applying conformity rules and expectations just don't work for them either as individuals nor in general, when organizing conformity oriented campaigns to increase diversity. 

  I believe I explored all the paths much further than people (notably managers and senior leads) can realize, and the choices I make are not that rondom as they seem to be. It's just that there are not that many of choices left to navigate between. I believe my experience as a software engineer is quite unique.

.

That's a lot! 

Every one of them would be fine, but all of them together was just too much. And [you've been worn before](https://matrix.to/#/!gGjMmeyQavLEcOoVQX:chagai.website/$AQSgoKis8ge_5TISn37fMsDelnr8X1XCH9FFI9fklbA?via=matrix.org&via=chagai.website&via=feneas.org) that you may be pushing my boundaries too much.

I am glad that as part of the discussion in this PR you could gain better understanding of hospitality exchange domain. And I appreciate your contribution to clarify WS domain model.

If you were ok with this, we may use parts of the text you've written.

I'll be also happy to use your knowledge and advocacy in ActivityPub and federation, but please respect my (extended to the project) autonomy in other domains.

Thanks for your understanding! 
I am closing this PR.

2021-07-09 11:48 UTC, closed without merging

2021-07-09 14:20 UTC, aschrijver commented
Oh wow, a lot of things absolutely not intended, and quite possibly misinterpreted. I've no qualms at all to see this closed, and we'll talk things over in a chat as you offered.

2021-07-10 09:35 UTC, nicksellen commented
I really appreciate these topics being discussed. From my experience when working on projects from our heart/soul they will likely involve a lot more emotions than normal-economy projects, and this in turn requires a lot of skills that are not widespread.

Because of that I welcome a bit of "mess" or "noise" in this process, nudging us into areas that can feel uncomfortable, then finding a way forward, _through_ the intensity. I have come to _love_ the model of **harmony** &rarr; **disharmony** &rarr; **repair** (originally from personal relationship topics, but I think applies much more widely), and with that, one idea is to accept the disharmony, then focus on the repair. (I won't delve more into it here, but "emotional awareness in software projects" is one of the most exciting topics to me lately!).

2021-07-10 09:42 UTC, nicksellen commented
just two specific points in reply to @aschrijver :

> you and the others most likely want to just join the fun and start to code

I think I am part of "the others"? If so, that is not an accurate assessment of me, and I don't get that impression from @mariha either (she has already done a lot of work that is not especially "fun").

> Personally I am still in the situation where I am doing too much advocacy and community things across the fedi to get to the coding fun

If you are doing _**too much** advocacy and community things_, please make sure to take care of yourself, or this can be a pathway to burnout and frustration, I think [your own advice](https://matrix.to/#/!gGjMmeyQavLEcOoVQX:chagai.website/$FjNtoz8al5ERYR9L7AKN4KS098fK7H4TUyxuGIOxfI0?via=matrix.org&via=chagai.website&via=feneas.org) (which was to @mariha originally) seems really fitting:

> So I'd just relax, and do some of the coding you love, and combine with other stuff as it comes up and you are in for it.

2021-07-11 13:58 UTC, aschrijver commented
For the first part I just mean that the back and forth on how to formulate, and how to best set up things - doing this async + remotely and mostly in text exchanges (and where a risk for misinterpretation entices to write even more text) - is time-consuming and I got multiple "let's get started" signals (at least as I interpreted).

On that "too much", that refers more to my own plans to work on some other projects (e.g. Groundwork), not on getting overworked or something. And I know my own advice was fitting :smile: it was also the conclusion of my own comment. But thank you for your consideration nonetheless :)